# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "austinbutler/archlinux-gui-x86_64"

  config.vm.synced_folder "data", "/vagrant_data"

  config.vm.provider "virtualbox" do |v|
      v.name = "Arch Sandbox GUI"
      v.gui = true
      # setextradata "Arch Linux" "CustomVideoMode1" "1360x768x24"
      # v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
      # video=1980x1024
      v.customize ["setextradata", v.name, "CustomVideoMode1", "1980x1024x24"]

      # Customize the amount of memory on the VM:
      v.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo 'hello'
  SHELL

end
